### ISSUE TITLE
Dark mode is incomplete

### ISSUE THREAD

**Issue by psobolewskiPhD** [melissawm/napari-theme-var#12]
Very minor: The theme advertises a dark mode, but it's incomplete?
<img width="1168" alt="image" src="https://github.com/melissawm/napari-theme-var/assets/76622105/66960781-d683-442c-b154-f544e27d3220">

**Comment by melissawm** [comment]
Currently, I've overriden the black theme with the existing light theme because I believe we need some design work to figure out the dark theme properly considering accessibility and usability. I will leave this issue open but won't address it just now.

**Comment by melissawm** [comment]
Will be resolved in napari/napari-sphinx-theme
