### ISSUE TITLE
[Small bug] At smaller window widths, the version switcher and GitHub logo pop out of the nav bar

### ISSUE THREAD

**Issue by psobolewskiPhD** [melissawm/napari-theme-var#19]
This happens in the intermediate stage between full top bar and just the burger, when the right-side ToC (internal links which I **LOVE**) collapses:
<img width="1251" alt="image" src="https://github.com/melissawm/napari-theme-var/assets/76622105/7e1db0fb-4679-4aea-a03d-e2c05457949e">

Safari 17, macOS

(This is a real nitpick--Have I posted enough about how many awesome fixes this has?)

**Comment by psobolewskiPhD** [comment]
Happens on Chrome too, just a bit earlier:
<img width="1259" alt="image" src="https://github.com/melissawm/napari-theme-var/assets/76622105/86ab10da-1086-4d27-8df6-ed91c94cc08b">

**Comment by psobolewskiPhD** [comment]
BTW the API reference looks fantastic 🎉

**Comment by melissawm** [comment]
This is an upstream issue, we'll keep track of it at pydata-sphinx-theme
