### ISSUE TITLE
[Gallery] The Gallery doesn't show previews just the napari logo

### ISSUE THREAD

**Issue by psobolewskiPhD** [melissawm/napari-theme-var#20]
Maybe this is just due to the build process? But I wanted to note it somewhere.
<img width="1344" alt="image" src="https://github.com/melissawm/napari-theme-var/assets/76622105/93f281f6-fffd-4645-96b1-c0767fb18c75">

**Comment by psobolewskiPhD** [comment]
Opening a page ( first one ) there is no preview there either.
However, I love the contrasty code highlighting:
<img width="1344" alt="image" src="https://github.com/melissawm/napari-theme-var/assets/76622105/0ccbc74f-97f0-468e-8f0d-8b21a230c2d8">
Looks very snazzy and snappy!

**Comment by melissawm** [comment]
I belive this happens because I am just copying the files over to gh-pages for you folks to see but it does work fine locally. I'm leaving this open to observe later but I don't think it's an actual issue.

**Comment by melissawm** [comment]
Solved
